services:
  polykey-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "50051:50051"
    environment:
      - POLYKEY_ENV=docker
      - POLYKEY_LOG_LEVEL=debug
    networks:
      - polykey-network
    healthcheck:
      # Use CMD-SHELL to better isolate the health check process
      test: ["CMD-SHELL", "grpc_health_probe -addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  polykey-dev-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-client
    environment:
      - POLYKEY_SERVER_ADDR=polykey-server:50051
      - POLYKEY_ENV=docker
      - POLYKEY_LOG_LEVEL=debug
    depends_on:
      polykey-server:
        condition: service_healthy
    networks:
      - polykey-network
    profiles:
      - dev

networks:
  polykey-network:
    driver: bridge
