# File: .github/workflows/reusable-docker-build.yml
name: Reusable Docker Build & Push

on:
  workflow_call:
    # This workflow can be called with inputs
    inputs:
      tag:
        description: 'The Docker tag to apply to the image'
        required: true
        type: string
    # It can also pass secrets
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
