name: PolyKey CI (Go Build & Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go 1.24.1
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.1

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install protoc compiler
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install protoc Go plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

    - name: Ensure GOPATH/bin is in PATH
      run: echo "${{ env.GOPATH }}/bin" >> $GITHUB_PATH

    - name: Generate Go code from .proto files
      run: go generate ./...

    - name: Build the project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
